version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(gha)"
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker)"
    labels:
      - dependencies
      - docker
