name: Bug report
description: Report a reproducible problem to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: checks
    attributes:
      label: Preliminary checks
      options:
        - label: I have searched existing issues
          required: true
        - label: I have read the README and checked the Notes section
          required: true
  - type: input
    id: version
    attributes:
      label: Image version/tag
      description: e.g., docker-latex:latest or sha
      placeholder: latest
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Describe the bug clearly
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the problem
      placeholder: |
        1. ...
        2. ...
        3. ...
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/output
      description: Paste error messages or attach logs
      render: shell
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      multiple: false
      options:
        - macOS
        - Linux
        - Windows
  - type: checkboxes
    id: security
    attributes:
      label: Is this a security issue?
      options:
        - label: If yes, please instead report privately per SECURITY.md
