name: Markdownlint

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.*'
  push:
    branches:
      - main
      - development
    paths:
      - '**/*.md'
      - '.markdownlint.*'

permissions:
  contents: read

jobs:
  lint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
